<h3>Editando Funcionario</h3>

<br/>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('loja-admin-interna', array('controller'=>'funcionario','id'=>$form->get('id_funcionario')->getValue(),'action'=>'edit')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_funcionario'));
echo $this->formRow($form->get('nome_funcionario')).'<br/>'; 
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


