<h1>funcionarios</h1>
<br/>
<p>
    <a href="<?php echo $this->url('loja-admin',array('controller'=>'funcionario','action'=>'new'));?>">Novo</a>
</p>

    <table class="table table-bordered table-responsive">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>
    <?php foreach($this->list as $entity): ?>
    <tr>
        <td><?php echo $entity->getIdFuncionario();?></td>
        <td><?php echo $entity->getNomeFuncionario();?></td>
        <td>
            <a class="btn btn-primary" href="<?php echo $this->url('loja-admin-interna',
                    array('controller'=>'funcionario', 'action'=>'edit','id'=>$entity->getIdFuncionario()));?>">Editar</a>
                   <a class="btn btn-primary btn-danger" href="<?php echo $this->url('loja-admin-interna',
                    array('controller'=>'funcionario', 'action'=>'delete','id'=>$entity->getIdFuncionario()));?>">Deletar</a>
        </td>
    </tr>
    <?php endforeach; ?> 
</table>
